# APIs

Instead of downloading World Bank data via a csv file, you're going to download the data using the World Bank APIs. The purpose of this exercise is to gain experience with another way of extracting data.

API is an acronym that stands for application programming interface. API’s provide a standardized way for two applications to talk to each other. In this case, the applications communicating with each other are the server application where World Bank stores data and your Jupyter notebook.

If you wanted to pull data directly from the World Bank’s server, you’d have to know what database system the World Bank was using. You’d also need permission to log in directly to the server, which would be a security risk for the World Bank. And if the World Bank ever migrated its data to a new system, you would have to rewrite all of your code again. The API allows you to execute code on the World Bank server without getting direct access.

# Before there were APIs

Before there were APIs, there was web scraping. People would download html directly from a website and then parse the results programatically. This practice is in a legal grey area. One reason that APIs became popular was so that companies could provide data to users and discourage web scraping.

Here are a few articles about the legality of web scraping.

* [QVC Can't Stop Web Scraping](https://www.forbes.com/sites/ericgoldman/2015/03/24/qvc-cant-stop-web-scraping/#120db59b3ca3)
* [Quora - Legality of Web Scraping](https://www.quora.com/What-is-the-legality-of-web-scraping)

All sorts of companies have public facing APIs including Facebook, Twitter, Google and Pinterest. You can pull data from these companies to create your own applications.

In this notebook, you’ll get practice using Python to pull data from the World Bank indicators API.

Here are links to information about the World Bank indicators and projects APIs if you want to learn more:
* [World Bank Indicators API](https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation)
* [World Bank Projects API](http://search.worldbank.org/api/v2/projects)

# Using APIs

In general, you access APIs via the web using a web address. Within the web address, you specify the data that you want. To know how to format the web address, you need to read an API's documentation. Some APIs also require that you send login credentials as part of your request. The World Bank APIs are public and do not require login credentials.

The Python requests library makes working with APIs relatively simple.

# Example Indicators API

Run the code example below to request data from the World Bank Indicators API. According to the documentation, you format your request url like so:

`http://api.worldbank.org/v2/countries/` + list of country abbreviations separated by ; + `/indicators/` + indicator name + `?` + options

where options can include
* per_page - number of records to return per page
* page - which page to return - eg if there are 5000 records and 100 records per page
* date - filter by dates
* format - json or xml
 
 and a few other options that you can read about [here](https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structure).

In [1]:
import requests
import pandas as pd

url = 'http://api.worldbank.org/v2/countries/br;cn;us;de/indicators/SP.POP.TOTL/?format=json&per_page=1000'
r = requests.get(url)
r.json()

[{'page': 1,
  'pages': 1,
  'per_page': 1000,
  'total': 244,
  'sourceid': '2',
  'sourcename': 'World Development Indicators',
  'lastupdated': '2021-06-30'},
 [{'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2020',
   'value': 212559409,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2019',
   'value': 211049519,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2018',
   'value': 209469320,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2017',
   'value': 207833825,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2016',
   'value': 206163056,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2015',
   'value': 204471759,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2014',
   'value': 202763744,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2013',
   'value': 201035904,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2012',
   'value': 199287292,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2011',
   'value': 197514541,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2010',
   'value': 195713637,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2009',
   'value': 193886505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2008',
   'value': 192030362,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2007',
   'value': 190130445,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2006',
   'value': 188167353,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2005',
   'value': 186127108,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2004',
   'value': 184006479,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2003',
   'value': 181809244,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2002',
   'value': 179537523,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2001',
   'value': 177196051,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2000',
   'value': 174790339,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1999',
   'value': 172318674,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1998',
   'value': 169785253,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1997',
   'value': 167209046,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1996',
   'value': 164614682,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1995',
   'value': 162019889,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1994',
   'value': 159432717,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1993',
   'value': 156849086,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1992',
   'value': 154259382,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1991',
   'value': 151648007,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1990',
   'value': 149003225,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1989',
   'value': 146328305,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1988',
   'value': 143627505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1987',
   'value': 140891606,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1986',
   'value': 138108915,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1985',
   'value': 135274083,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1984',
   'value': 132383569,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1983',
   'value': 129448815,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1982',
   'value': 126498322,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1981',
   'value': 123570327,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1980',
   'value': 120694012,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1979',
   'value': 117878412,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1978',
   'value': 115121158,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1977',
   'value': 112425392,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1976',
   'value': 109790943,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1975',
   'value': 107216209,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1974',
   'value': 104706193,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1973',
   'value': 102259497,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1972',
   'value': 99859388,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1971',
   'value': 97482928,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1970',
   'value': 95113265,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1969',
   'value': 92746607,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1968',
   'value': 90387079,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1967',
   'value': 88035815,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1966',
   'value': 85696502,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1965',
   'value': 83373533,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1964',
   'value': 81064572,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1963',
   'value': 78772647,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1962',
   'value': 76514329,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1961',
   'value': 74311338,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1960',
   'value': 72179235,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2020',
   'value': 1402112000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2019',
   'value': 1397715000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2018',
   'value': 1392730000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2017',
   'value': 1386395000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2016',
   'value': 1378665000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2015',
   'value': 1371220000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2014',
   'value': 1364270000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2013',
   'value': 1357380000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2012',
   'value': 1350695000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2011',
   'value': 1344130000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2010',
   'value': 1337705000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2009',
   'value': 1331260000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2008',
   'value': 1324655000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2007',
   'value': 1317885000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2006',
   'value': 1311020000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2005',
   'value': 1303720000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2004',
   'value': 1296075000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2003',
   'value': 1288400000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2002',
   'value': 1280400000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2001',
   'value': 1271850000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2000',
   'value': 1262645000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},

This json data isn't quite ready for a pandas data frame. Notice that the json response is a list with two entries. The first entry is 
```
{'lastupdated': '2018-06-28',
  'page': 1,
  'pages': 1,
  'per_page': 1000,
  'total': 232}
```

That first entry is meta data about the results. For example, it says that there is one page returned with 232 results. 

The second entry is another list containing the data. This data would need some cleaning to be used in a pandas data frame. That would happen later in the transformation step of an ETL pipeline. Run the cell below to read the results into a dataframe and see what happens.

In [2]:
###
# Run this cell that converts the json into a dataframe
# Note that you do not need the pd.read_json() method because this is not a file or a string containing json 
##

pd.DataFrame(r.json()[1])

,country,countryiso3code,date,decimal,indicator,obs_status,unit,value
0,"{'id': 'BR', 'value': 'Brazil'}",BRA,2020,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,212559409
1,"{'id': 'BR', 'value': 'Brazil'}",BRA,2019,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,211049519
2,"{'id': 'BR', 'value': 'Brazil'}",BRA,2018,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,209469320
3,"{'id': 'BR', 'value': 'Brazil'}",BRA,2017,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,207833825
4,"{'id': 'BR', 'value': 'Brazil'}",BRA,2016,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,206163056
5,"{'id': 'BR', 'value': 'Brazil'}",BRA,2015,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,204471759
6,"{'id': 'BR', 'value': 'Brazil'}",BRA,2014,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,202763744
7,"{'id': 'BR', 'value': 'Brazil'}",BRA,2013,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,201035904
8,"{'id': 'BR', 'value': 'Brazil'}",BRA,2012,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,199287292
9,"{'id': 'BR', 'value': 'Brazil'}",BRA,2011,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,197514541
10,"{'id': 'BR', 'value': 'Brazil'}",BRA,2010,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,195713637
11,"{'id': 'BR', 'value': 'Brazil'}",BRA,2009,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,193886505
12,"{'id': 'BR', 'value': 'Brazil'}",BRA,2008,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,192030362
13,"{'id': 'BR', 'value': 'Brazil'}",BRA,2007,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,190130445
14,"{'id': 'BR', 'value': 'Brazil'}",BRA,2006,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,188167353
15,"{'id': 'BR', 'value': 'Brazil'}",BRA,2005,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,186127108
16,"{'id': 'BR', 'value': 'Brazil'}",BRA,2004,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,184006479
17,"{'id': 'BR', 'value': 'Brazil'}",BRA,2003,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,181809244
18,"{'id': 'BR', 'value': 'Brazil'}",BRA,2002,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,179537523
19,"{'id': 'BR', 'value': 'Brazil'}",BRA,2001,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,177196051
20,"{'id': 'BR', 'value': 'Brazil'}",BRA,2000,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,174790339
21,"{'id': 'BR', 'value': 'Brazil'}",BRA,1999,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,172318674
22,"{'id': 'BR', 'value': 'Brazil'}",BRA,1998,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,169785253
23,"{'id': 'BR', 'value': 'Brazil'}",BRA,1997,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,167209046
24,"{'id': 'BR', 'value': 'Brazil'}",BRA,1996,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,164614682
25,"{'id': 'BR', 'value': 'Brazil'}",BRA,1995,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,162019889
26,"{'id': 'BR', 'value': 'Brazil'}",BRA,1994,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,159432717
27,"{'id': 'BR', 'value': 'Brazil'}",BRA,1993,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,156849086
28,"{'id': 'BR', 'value': 'Brazil'}",BRA,1992,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,154259382
29,"{'id': 'BR', 'value': 'Brazil'}",BRA,1991,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,151648007
...,...,...,...,...,...,...,...,...
214,"{'id': 'US', 'value': 'United States'}",USA,1989,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,246819000
215,"{'id': 'US', 'value': 'United States'}",USA,1988,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,244499000
216,"{'id': 'US', 'value': 'United States'}",USA,1987,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,242289000
217,"{'id': 'US', 'value': 'United States'}",USA,1986,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,240133000
218,"{'id': 'US', 'value': 'United States'}",USA,1985,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,237924000
219,"{'id': 'US', 'value': 'United States'}",USA,1984,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,235825000
220,"{'id': 'US', 'value': 'United States'}",USA,1983,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,233792000
221,"{'id': 'US', 'value': 'United States'}",USA,1982,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,231664000
222,"{'id': 'US', 'value': 'United States'}",USA,1981,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,229466000
223,"{'id': 'US', 'value': 'United States'}",USA,1980,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,227225000
224,"{'id': 'US', 'value': 'United States'}",USA,1979,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,225055000
225,"{'id': 'US', 'value': 'United States'}",USA,1978,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,222585000
226,"{'id': 'US', 'value': 'United States'}",USA,1977,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,220239000
227,"{'id': 'US', 'value': 'United States'}",USA,1976,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,218035000
228,"{'id': 'US', 'value': 'United States'}",USA,1975,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,215973000
229,"{'id': 'US', 'value': 'United States'}",USA,1974,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,213854000
230,"{'id': 'US', 'value': 'United States'}",USA,1973,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,211909000
231,"{'id': 'US', 'value': 'United States'}",USA,1972,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,209896000
232,"{'id': 'US', 'value': 'United States'}",USA,1971,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,207661000
233,"{'id': 'US', 'value': 'United States'}",USA,1970,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,205052000
234,"{'id': 'US', 'value': 'United States'}",USA,1969,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,202677000
235,"{'id': 'US', 'value': 'United States'}",USA,1968,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,200706000
236,"{'id': 'US', 'value': 'United States'}",USA,1967,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,198712000
237,"{'id': 'US', 'value': 'United States'}",USA,1966,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,196560000
238,"{'id': 'US', 'value': 'United States'}",USA,1965,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,194303000
239,"{'id': 'US', 'value': 'United States'}",USA,1964,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,191889000
240,"{'id': 'US', 'value': 'United States'}",USA,1963,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,189242000
241,"{'id': 'US', 'value': 'United States'}",USA,1962,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,186538000
242,"{'id': 'US', 'value': 'United States'}",USA,1961,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,183691000
243,"{'id': 'US', 'value': 'United States'}",USA,1960,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,180671000

There are some issues with this dataframe. The country and indicator variables don't look particularly useful in their current form. Again, dealing with those issues would come in the transformation phase of a pipeline, which comes later in the lesson.

# Exercise Indicators API

Use the Indicators API to request rural population data for Switzerland in the years 1995 through 2001. Here are a few helpful resources:
* [documentation included how to filter by year](https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structure)
* [2-character iso country codes](https://www.nationsonline.org/oneworld/country_code_list.htm)
* [search box for World Bank indicators](https://data.worldbank.org)

To find the indicator code, first search for the indicator here: https://data.worldbank.org
Click on the indicator name. The indicator code is in the url. For example, the indicator code for total population is SP.POP.TOTL, which you can see in the link [https://data.worldbank.org/indicator/SP.RUR.TOTL](https://data.worldbank.org/indicator/SP.RUR.TOTL).

In [6]:
# TODO: get the url ready
url = 'http://api.worldbank.org/v2/countries/ch;/indicators/SP.RUR.TOTL.?format=json&per_page=1000&date<=2001&date>=1995'

# TODO: send the request
s = requests.get(url)
s.json()

# TODO: output the json using the json method like in the previous example

[{'page': 1,
  'pages': 1,
  'per_page': 1000,
  'total': 183,
  'sourceid': '2',
  'sourcename': 'World Development Indicators',
  'lastupdated': '2021-06-30'},
 [{'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 428130824,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 420506755,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 412813896,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 405073414,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 397309170,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 389549737,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 381804769,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 374087585,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 366421044,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 358859175,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 351555624,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 344360035,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 337282123,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 330345945,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 322898173,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 315978640,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 309309701,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 302759083,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 296373566,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 290144369,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 283976874,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 277852216,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 271831042,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 265941536,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 260220030,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 254619140,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 249116284,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 243765319,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 238735353,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 233766631,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 228732089,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 223776498,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 218713996,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 213673208,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 208676190,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 203781778,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 198929259,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 194110018,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 189316575,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 184570451,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 179924021,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': 175378958,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': 171027348,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': 166861812,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': 162787823,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': 158801992,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': 154904194,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': 151094561,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': 147420415,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': 143873332,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': 140429572,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': 137101283,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': 133924817,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': 130848646,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': 127863551,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': 124963818,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': 122140071,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': 119394205,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': 116717022,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1961',
   'value': 114110332,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1960',
   'value': 111597625,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 239272321,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 235777809,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 232268264,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 228753833,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 225245547,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 221750635,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 218280270,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 214830600,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 211404928,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 208012011,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 204634498,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 201273304,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 197915597,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 194584736,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.RUR.TOTL', 'value': 'Rural population'},
   'country': {'id': '  ', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 191308868,
   'unit': '',
   'obs_status': '',
   'decimal': 0},

In [7]:
pd.DataFrame(s.json()[1])

,country,countryiso3code,date,decimal,indicator,obs_status,unit,value
0,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2020,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,428130824
1,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2019,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,420506755
2,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2018,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,412813896
3,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2017,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,405073414
4,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2016,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,397309170
5,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2015,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,389549737
6,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2014,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,381804769
7,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2013,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,374087585
8,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2012,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,366421044
9,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2011,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,358859175
10,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2010,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,351555624
11,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2009,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,344360035
12,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2008,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,337282123
13,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2007,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,330345945
14,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2006,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,322898173
15,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2005,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,315978640
16,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2004,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,309309701
17,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2003,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,302759083
18,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2002,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,296373566
19,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2001,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,290144369
20,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,2000,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,283976874
21,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1999,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,277852216
22,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1998,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,271831042
23,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1997,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,265941536
24,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1996,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,260220030
25,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1995,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,254619140
26,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1994,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,249116284
27,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1993,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,243765319
28,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1992,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,238735353
29,"{'id': ' ', 'value': 'Africa Eastern and Sout...",AFE,1991,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,233766631
...,...,...,...,...,...,...,...,...
153,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1989,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1729128
154,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1988,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1711247
155,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1987,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1694724
156,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1986,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1680210
157,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1985,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1667607
158,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1984,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1656461
159,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1983,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1646672
160,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1982,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1635792
161,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1981,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1622449
162,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1980,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1612903
163,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1979,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1609847
164,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1978,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1610009
165,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1977,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1613257
166,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1976,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1622138
167,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1975,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1634860
168,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1974,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1639000
169,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1973,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1633603
170,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1972,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1624969
171,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1971,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1615981
172,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1970,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1616732
173,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1969,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1622399
174,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1968,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1621354
175,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1967,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1618201
176,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1966,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1615259
177,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1965,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1615391
178,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1964,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1613632
179,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1963,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1603842
180,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1962,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1586363
181,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1961,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1562740
182,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1960,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1549119